install: |-
    sudo apt-get update
    sudo apt-get install -y libmagic-dev zlib1g-dev
    sudo apt-get install -y ruby ruby-dev
    sudo apt-get install -y libmagic-dev
    sudo apt-get install -y bsdmainutils
    sudo gem update && gem install nokogiri && gem install bundler
architect:
  - LeanderK
  - jundl77
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
docker:
  image: "teamed/docker-java-8"
release:
  commanders:
      - LeanderK
      - jundl77
  script: |-
    git config --global user.email "Leander.Kurscheidt@gmx.de"
    git config --global user.name "Leander Kurscheidt"
    git config --global credential.helper 'cache --timeout 600'
    mvn versions:set "-DnewVersion=${tag//\'}"
    git commit -am "${tag//\'}"
    mvn clean deploy --settings /home/r/settings.xml